---
apiVersion: v1
kind: Namespace
metadata:
  name: env

---
apiVersion: v3
kind: Service
metadata:
  name: tc-svc
spec:
  selector:
    app: tomcat
    name: env
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30003
  type: NodePort

---
apiVersion: v1

kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: 
  password: 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tomcat
      name: env
  template:
    metadata:
      labels:
        app: tomcat
        name: mysecret
    spec:
      volumes:
      - name: volume 
        hostpath: /anusha/data
      containers:
      - name: gol
        image: 587282778384.dkr.ecr.us-east-1.amazonaws.com/docker:lates
        ports:
          - containerPort: 8080
            protocol: TCP
        volumeMounts:
          - name: volume 
            mountPath: /anusha
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aut-scale
  namespace:
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dep
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0003
spec:
  capacity:
    storage: 2gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    
    path: /tmp
    
